export type Language = 'en' | 'te';

export type TranslatedText = {
  [key in Language]: string;
};

export interface Destination {
  id: string;
  slug: string;
  name: TranslatedText;
  description: TranslatedText;
  image: string;
  dataAiHint: string;
  regionTags: string[];
  historicalSignificance: TranslatedText;
  bestTimeToVisit: TranslatedText;
  localCuisine: TranslatedText;
  culturalEvents: TranslatedText;
  distanceFromHyderabad: string | null;
  extraImages: { url: string, hint: string }[];
  type: 'telangana' | 'india';
}

export const telanganaDestinations: Destination[] = [
  {
    id: "charminar",
    slug: "charminar",
    name: { en: "Charminar", te: "చార్మినార్" },
    description: { en: "A historic monument and mosque in Hyderabad, an icon of the city.", te: "హైదరాబాద్‌లోని ఒక చారిత్రాత్మక స్మారక చిహ్నం మరియు మసీదు, నగరానికి ఒక చిహ్నం." },
    image: "https://images.unsplash.com/photo-1441911645956-df6e9bbc5496?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjaGFybWluYXJ8ZW58MHx8fHwxNzUzNTQ4MDU1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "charminar hyderabad",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "The Charminar, an iconic monument and mosque located in the heart of Hyderabad, was constructed in 1591 by Muhammad Quli Qutb Shah, the fifth ruler of the Qutb Shahi dynasty. He built it to commemorate the end of a deadly plague epidemic in the city. Legend has it that he prayed for the end of the plague and vowed to build a mosque at the very place he was praying. The four grand arches and four minarets represent the four caliphs of Islam.", te: "హైదరాబాద్ నడిబొడ్డున ఉన్న ఒక ఐకానిక్ స్మారక చిహ్నం మరియు మసీదు అయిన చార్మినార్, కుతుబ్ షాహీ రాజవంశం యొక్క ఐదవ పాలకుడు ముహమ్మద్ కులీ కుతుబ్ షా చే 1591లో నిర్మించబడింది. నగరంలో ఒక ప్రాణాంతకమైన ప్లేగు మహమ్మారి ముగింపుకు గుర్తుగా దీనిని నిర్మించాడు. పురాణాల ప్రకారం, అతను ప్లేగు ముగింపు కోసం ప్రార్థించి, తాను ప్రార్థిస్తున్న ప్రదేశంలోనే ఒక మసీదును నిర్మిస్తానని ప్రతిజ్ఞ చేసాడు. నాలుగు గొప్ప ఆర్చ్‌లు మరియు నాలుగు మినార్లు ఇస్లాం యొక్క నలుగురు ఖలీఫాలను సూచిస్తాయి." },
    bestTimeToVisit: { en: "October to March, to avoid the heat.", te: "వేడిని నివారించడానికి అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Hyderabadi Biryani, Haleem, Irani Chai.", te: "హైదరాబాదీ బిర్యానీ, హలీమ్, ఇరానీ చాయ్." },
    culturalEvents: { en: "Ramadan festivities, various cultural festivals.", te: "రంజాన్ ఉత్సవాలు, వివిధ సాంస్కృతిక పండుగలు." },
    distanceFromHyderabad: "Located in the heart of Hyderabad city.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "charminar architecture" }, { url: "https://placehold.co/400x300.png", hint: "hyderabad market" }],
    type: 'telangana',
  },
  {
    id: "golconda-fort",
    slug: "golconda-fort",
    name: { en: "Golconda Fort", te: "గోల్కొండ కోట" },
    description: { en: "A magnificent fortress complex known for its acoustics and grandeur.", te: "ధ్వనిశాస్త్రం మరియు వైభవానికి ప్రసిద్ధి చెందిన అద్భుతమైన కోట సముదాయం." },
    image: "https://images.unsplash.com/photo-1575492534537-792e4e1b8bed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxGb3J0fGVufDB8fHx8MTc1MzYwMzU0NHww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "golconda fort",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Golconda Fort's origins trace back to the Kakatiya dynasty in the 13th century. It was later fortified and expanded by the Qutb Shahi kings, who ruled the region for nearly 170 years. The fort was a major center for the diamond trade, producing some of the world's most famous gems, including the Koh-i-Noor. Its ingenious acoustic system, where a clap at the entrance can be heard at the highest point, and its elaborate water supply system showcase the advanced engineering of its time.", te: "గోల్కొండ కోట యొక్క మూలాలు 13వ శతాబ్దంలో కాకతీయ రాజవంశానికి చెందినవి. తరువాత దాదాపు 170 సంవత్సరాలు ఈ ప్రాంతాన్ని పరిపాలించిన కుతుబ్ షాహీ రాజులచే ఇది పటిష్టం చేయబడి, విస్తరించబడింది. కోహినూర్‌తో సహా ప్రపంచంలోని అత్యంత ప్రసిద్ధ రత్నాలలో కొన్నింటిని ఉత్పత్తి చేసిన ఈ కోట వజ్రాల వ్యాపారానికి ప్రధాన కేంద్రంగా ఉండేది. దాని ప్రవేశ ద్వారం వద్ద ఒక చప్పట్లు కొడితే అత్యంత ఎత్తైన ప్రదేశంలో వినబడే దాని తెలివైన ధ్వని వ్యవస్థ, మరియు దాని విస్తృతమైన నీటి సరఫరా వ్యవస్థ దాని కాలపు అధునాతన ఇంజనీరింగ్‌ను ప్రదర్శిస్తాయి." },
    bestTimeToVisit: { en: "September to March.", te: "సెప్టెంబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Pathar ka Gosht, Kebabs.", te: "పత్తర్ కా గోష్ట్, కబాబ్స్." },
    culturalEvents: { en: "Sound and Light Show in the evenings.", te: "సాయంత్రం సౌండ్ అండ్ లైట్ షో." },
    distanceFromHyderabad: "Approx. 11 km from Hyderabad city center.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "fortress walls" }, { url: "https://placehold.co/400x300.png", hint: "fort ruins" }],
    type: 'telangana',
  },
  {
    id: "husain-sagar-lake",
    slug: "husain-sagar-lake",
    name: { en: "Hussain Sagar Lake", te: "హుస్సేన్ సాగర్ సరస్సు" },
    description: { en: "A heart-shaped lake with a large monolithic statue of the a Buddha in its center.", te: "మధ్యలో గౌతమ బుద్ధుని పెద్ద ఏకశిలా విగ్రహంతో ఉన్న హృదయాకార సరస్సు." },
    image: "https://images.unsplash.com/photo-1712422813106-dfb845a8a7ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxIdXNzYWluJTIwU2FnYXIlMjBMYWtlfGVufDB8fHx8MTc1MzYwMzY0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "hussain sagar",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Built in 1563 during the reign of Ibrahim Quli Qutb Shah, Hussain Sagar is an artificial lake fed by the River Musi. It was constructed to meet the water and irrigation needs of the city. The large monolithic statue of Gautama Buddha, standing on a platform in the middle of the lake, was erected in 1992, adding to its charm and becoming a significant landmark.", te: "ఇబ్రహీం కులీ కుతుబ్ షా పాలనలో 1563లో నిర్మించబడిన హుస్సేన్ సాగర్, మూసీ నది ద్వారా నీరు అందించబడే ఒక కృత్రిమ సరస్సు. ఇది నగర నీటి మరియు నీటిపారుదల అవసరాలను తీర్చడానికి నిర్మించబడింది. సరస్సు మధ్యలో ఒక వేదికపై నిలబడి ఉన్న గౌతమ బుద్ధుని పెద్ద ఏకశిలా విగ్రహం 1992లో ఏర్పాటు చేయబడింది, ఇది దాని ఆకర్షణను పెంచి ఒక ముఖ్యమైన మైలురాయిగా మారింది." },
    bestTimeToVisit: { en: "All year round, especially evenings.", te: "ఏడాది పొడవునా, ముఖ్యంగా సాయంత్రం వేళల్లో." },
    localCuisine: { en: "Street food around the lake, various restaurants nearby.", te: "సరస్సు చుట్టూ వీధి ఆహారం, సమీపంలోని వివిధ రెస్టారెంట్లు." },
    culturalEvents: { en: "Lumbini Park events, boating.", te: "లుంబిని పార్క్ కార్యక్రమాలు, బోటింగ్." },
    distanceFromHyderabad: "Located in the heart of Hyderabad.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "buddha statue" }, { url: "https://placehold.co/400x300.png", hint: "lake boating" }],
    type: 'telangana',
  },
  {
    id: "ramoji-film-city",
    slug: "ramoji-film-city",
    name: { en: "Ramoji Film City", te: "రామోజీ ఫిల్మ్ సిటీ" },
    description: { en: "The world's largest integrated film city and a popular tourism and recreation center.", te: "ప్రపంచంలోనే అతిపెద్ద ఇంటిగ్రేటెడ్ ఫిల్మ్ సిటీ మరియు ఒక ప్రసిద్ధ పర్యాటక మరియు వినోద కేంద్రం." },
    image: "https://images.unsplash.com/photo-1598610339755-6e4e24737a27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxSYW1vamklMjBmaWxtJTIwY2l0eXxlbnwwfHx8fDE3NTM1NDkyNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "film city",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Opened to the public in 1996 by Telugu film producer Ramoji Rao, Ramoji Film City is a vast integrated filmmaking facility. It holds the Guinness World Record for the largest film studio complex in the world. Beyond its function in cinema, it has become a major tourist attraction, offering recreations of famous landmarks, amusement parks, and behind-the-scenes tours of film sets.", te: "తెలుగు చిత్ర నిర్మాత రామోజీ రావుచే 1996లో ప్రజల కోసం తెరవబడిన రామోజీ ఫిల్మ్ సిటీ, ఒక విస్తారమైన ఇంటిగ్రేటెడ్ చిత్ర నిర్మాణ సౌకర్యం. ఇది ప్రపంచంలోనే అతిపెద్ద ఫిల్మ్ స్టూడియో కాంప్లెక్స్‌గా గిన్నిస్ వరల్డ్ రికార్డ్‌ను కలిగి ఉంది. సినిమాలోని దాని పనితీరుకు మించి, ఇది ఒక ప్రధాన పర్యాటక ఆకర్షణగా మారింది, ప్రసిద్ధ మైలురాళ్ల పునఃసృష్టి, అమ్యూజ్‌మెంట్ పార్కులు మరియు ఫిల్మ్ సెట్‌ల తెరవెనుక పర్యటనలను అందిస్తుంది." },
    bestTimeToVisit: { en: "Throughout the year.", te: "ఏడాది పొడవునా." },
    localCuisine: { en: "Multiple restaurants within the film city catering to various tastes.", te: "ఫిల్మ్ సిటీలో వివిధ రకాల అభిరుచులకు అనుగుణంగా బహుళ రెస్టారెంట్లు ఉన్నాయి." },
    culturalEvents: { en: "Live shows, stunt shows, and thematic events throughout the year.", te: "లైవ్ షోలు, స్టంట్ షోలు, మరియు ఏడాది పొడవునా థీమాటిక్ ఈవెంట్‌లు." },
    distanceFromHyderabad: "Approx. 30 km from Hyderabad.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "film set" }, { url: "https://placehold.co/400x300.png", hint: "amusement park" }],
    type: 'telangana',
  },
  {
    id: "qutb-shahi-tombs",
    slug: "qutb-shahi-tombs",
    name: { en: "Qutb Shahi Tombs", te: "కుతుబ్ షాహీ సమాధులు" },
    description: { en: "A complex of tombs and mosques built in memory of the rulers of the Qutb Shahi dynasty.", te: "కుతుబ్ షాహీ రాజవంశం యొక్క పాలకుల జ్ఞాపకార్థం నిర్మించిన సమాధులు మరియు మసీదుల సముదాయం." },
    image: "https://images.unsplash.com/photo-1644326792898-d7c455000679?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxUb21ic3xlbnwwfHx8fDE3NTM2MDM4NDh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "historic tombs",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Located near the famous Golconda Fort, the Qutb Shahi Tombs are the final resting place of the seven kings of the Qutb Shahi dynasty. These majestic structures are renowned for their unique architectural style, which is a blend of Persian, Pashtun, and Indian forms. Each tomb is a quadrangular structure, crowned by a dome and standing on a raised platform. The galleries of the larger tombs are covered with intricate stonework.", te: "ప్రసిద్ధ గోల్కొండ కోట సమీపంలో ఉన్న కుతుబ్ షాహీ సమాధులు, కుతుబ్ షాహీ రాజవంశం యొక్క ఏడుగురు రాజుల చివరి విశ్రాంతి స్థలం. ఈ గంభీరమైన నిర్మాణాలు పెర్షియన్, పష్టున్, మరియు భారతీయ రూపాల మిశ్రమమైన వారి ప్రత్యేకమైన వాస్తుశిల్పానికి ప్రసిద్ధి చెందాయి. ప్రతి సమాధి ఒక చతుర్భుజ నిర్మాణం, ఒక గుమ్మటంతో కిరీటధారణ చేయబడి ఒక ఎత్తైన వేదికపై నిలబడి ఉంటుంది. పెద్ద సమాధుల గ్యాలరీలు క్లిష్టమైన రాతిపనితో కప్పబడి ఉంటాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Local eateries near Golconda Fort.", te: "గోల్కొండ కోట సమీపంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A place of historical interest and reflection.", te: "చారిత్రక ఆసక్తి మరియు ప్రతిబింబం యొక్క ప్రదేశం." },
    distanceFromHyderabad: "Approx. 12 km from Hyderabad city center.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "tomb architecture" }, { url: "https://placehold.co/400x300.png", hint: "tomb dome" }],
    type: 'telangana',
  },
  {
    id: "warangal-fort",
    slug: "warangal-fort",
    name: { en: "Warangal Fort", te: "వరంగల్ కోట" },
    description: { en: "An ancient fort known for its impressive stone gateways (Kakatiya Kala Thoranam).", te: "దాని ఆకట్టుకునే రాతి ముఖద్వారాలకు (కాకతీయ కళా తోరణం) ప్రసిద్ధి చెందిన ఒక పురాతన కోట." },
    image: "https://images.unsplash.com/photo-1690796943027-72efe121234a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxXYXJhbmdhbCUyMGZvcnR8ZW58MHx8fHwxNzUzNjAzODgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "warangal fort",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "Warangal Fort, dating back to at least the 12th century, was the capital of the great Kakatiya dynasty. The fort was renowned for its three concentric circular walls and massive stone gateways. The most famous remnants are the Kakatiya Kala Thoranam, or arches, which have become a symbol of Telangana. The fort has witnessed many battles and has been ruled by various dynasties after the Kakatiyas, including the Delhi Sultanate and the Bahmani Sultanate.", te: "కనీసం 12వ శతాబ్దానికి చెందిన వరంగల్ కోట, గొప్ప కాకతీయ రాజవంశానికి రాజధానిగా ఉండేది. ఈ కోట దాని మూడు ఏకకేంద్ర వృత్తాకార గోడలు మరియు భారీ రాతి ముఖద్వారాలకు ప్రసిద్ధి చెందింది. అత్యంత ప్రసిద్ధ అవశేషాలు కాకతీయ కళా తోరణం, లేదా ఆర్చ్‌లు, ఇవి తెలంగాణకు చిహ్నంగా మారాయి. ఈ కోట అనేక యుద్ధాలను చూసింది మరియు కాకతీయుల తర్వాత ఢిల్లీ సుల్తానేట్ మరియు బహమనీ సుల్తానేట్‌తో సహా వివిధ రాజవంశాలచే పాలించబడింది." },
    bestTimeToVisit: { en: "September to April.", te: "సెప్టెంబర్ నుండి ఏప్రిల్ వరకు." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Local festivals and jatras.", te: "స్థానిక పండుగలు మరియు జాతరలు." },
    distanceFromHyderabad: "Approx. 145 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "kakatiya thoranam" }, { url: "https://placehold.co/400x300.png", hint: "fort ruins" }],
    type: 'telangana',
  },
  {
    id: "kakatiya-kala-thoranam",
    slug: "kakatiya-kala-thoranam",
    name: { en: "Kakatiya Kala Thoranam", te: "కాకతీయ కళా తోరణం" },
    description: { en: "The iconic stone archway of Warangal Fort, a symbol of the Kakatiya dynasty and the emblem of Telangana.", te: "వరంగల్ కోట యొక్క ఐకానిక్ రాతి తోరణం, కాకతీయ రాజవంశం యొక్క చిహ్నం మరియు తెలంగాణ రాష్ట్ర చిహ్నం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ancient archway",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "This ornate archway, located within the Warangal Fort complex, is a masterpiece of Kakatiyan architecture from the 12th century. It is one of four such gates that formed the entrances to a now-ruined great Shiva temple. Unlike the Dravidian-style gopurams common in South India, this thoranam (arch) is a unique architectural feature. The intricate carvings and its grand scale reflect the artistic prowess of the Kakatiya rulers. It has been officially incorporated into the emblem of Telangana state.", te: "వరంగల్ కోట సముదాయంలో ఉన్న ఈ అలంకరించబడిన తోరణం, 12వ శతాబ్దపు కాకతీయ వాస్తుశిల్పానికి ఒక కళాఖండం. ఇది ఇప్పుడు శిథిలమైన గొప్ప శివాలయానికి ప్రవేశ ద్వారాలుగా ఏర్పడిన నాలుగు అటువంటి గేట్లలో ఒకటి. దక్షిణ భారతదేశంలో సాధారణమైన ద్రావిడ-శైలి గోపురాల వలె కాకుండా, ఈ తోరణం ఒక ప్రత్యేకమైన వాస్తుశిల్ప లక్షణం. క్లిష్టమైన శిల్పాలు మరియు దాని గొప్ప స్థాయి కాకతీయ పాలకుల కళా నైపుణ్యాన్ని ప్రతిబింబిస్తాయి. ఇది అధికారికంగా తెలంగాణ రాష్ట్ర చిహ్నంలో చేర్చబడింది." },
    bestTimeToVisit: { en: "September to April.", te: "సెప్టెంబర్ నుండి ఏప్రిల్ వరకు." },
    localCuisine: { en: "Local Warangal cuisine.", te: "స్థానిక వరంగల్ వంటకాలు." },
    culturalEvents: { en: "Part of the Warangal Fort complex, a site of major historical significance.", te: "వరంగల్ కోట సముదాయంలో భాగం, ఇది ప్రధాన చారిత్రక ప్రాముఖ్యత కలిగిన ప్రదేశం." },
    distanceFromHyderabad: "Approx. 145 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "stone carving" }, { url: "https://placehold.co/400x300.png", hint: "archway detail" }],
    type: 'telangana',
  },
  {
    id: "pakhal-lake",
    slug: "pakhal-lake",
    name: { en: "Pakhal Lake", te: "పాకాల సరస్సు" },
    description: { en: "A man-made lake situated in the Pakhal Wildlife Sanctuary, surrounded by lush forests.", te: "పాకాల వన్యప్రాణుల అభయారణ్యంలో ఉన్న ఒక మానవ నిర్మిత సరస్సు, పచ్చని అడవులతో చుట్టుముట్టబడి ఉంది." },
    image: "https://images.unsplash.com/photo-1629378343801-abfbcaca500d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMnx8UGFraGFsJTIwTGFrZXxlbnwwfHx8fDE3NTM2MDM5Njd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "serene lake",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "Pakhal Lake is a man-made lake created in 1213 AD by the Kakatiya king Ganapati Deva. It was constructed by harnessing a small tributary of the Krishna River. The lake was built to serve as a source of irrigation for the surrounding agricultural lands. Today, it is nestled within the Pakhal Wildlife Sanctuary, providing a vital water source for the diverse flora and fauna of the region and offering picturesque views to visitors.", te: "పాకాల సరస్సు క్రీ.శ. 1213లో కాకతీయ రాజు గణపతి దేవునిచే సృష్టించబడిన ఒక మానవ నిర్మిత సరస్సు. కృష్ణా నది యొక్క ఒక చిన్న ఉపనదిని ఉపయోగించుకుని ఇది నిర్మించబడింది. ఈ సరస్సు చుట్టుపక్కల వ్యవసాయ భూములకు నీటిపారుదల వనరుగా పనిచేయడానికి నిర్మించబడింది. నేడు, ఇది పాకాల వన్యప్రాణుల అభయారణ్యంలో ఉంది, ఈ ప్రాంతంలోని విభిన్న వృక్షజాలం మరియు జంతుజాలానికి ఒక ముఖ్యమైన నీటి వనరును అందిస్తుంది మరియు సందర్శకులకు సుందరమైన దృశ్యాలను అందిస్తుంది." },
    bestTimeToVisit: { en: "November to June, for pleasant weather and wildlife spotting.", te: "నవంబర్ నుండి జూన్ వరకు, ఆహ్లాదకరమైన వాతావరణం మరియు వన్యప్రాణులను చూడటానికి." },
    localCuisine: { en: "Local eateries in nearby towns.", te: "సమీప పట్టణాలలో స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A popular spot for picnics, boating, and nature walks.", te: "పిక్నిక్‌లు, బోటింగ్, మరియు ప్రకృతి నడకలకు ఒక ప్రసిద్ధ ప్రదేశం." },
    distanceFromHyderabad: "Approx. 200 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "wildlife sanctuary" }, { url: "https://placehold.co/400x300.png", hint: "forest lake" }],
    type: 'telangana',
  },
  {
    id: "nagarjuna-sagar-dam",
    slug: "nagarjuna-sagar-dam",
    name: { en: "Nagarjuna Sagar Dam", te: "నాగార్జున సాగర్ డ్యాం" },
    description: { en: "One of the world's largest and tallest masonry dams, built across the Krishna river.", te: "ప్రపంచంలోనే అతిపెద్ద మరియు ఎత్తైన రాతి ఆనకట్టలలో ఒకటి, కృష్ణా నదిపై నిర్మించబడింది." },
    image: "https://images.unsplash.com/photo-1612444944202-b8a424ca7663?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxOYWdhcmp1bmElMjBTYWdhciUyMGRhbXxlbnwwfHx8fDE3NTM2MDQwNjd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "large dam",
    regionTags: ["Telangana", "Nalgonda"],
    historicalSignificance: { en: "Nagarjuna Sagar Dam is a monumental masonry dam built on the Krishna River. It was one of the earliest large-scale infrastructure projects of independent India, started in 1955 and completed by 1967. The dam created a massive reservoir, the Nagarjuna Sagar, which is the third largest man-made lake in the world. The project has been instrumental in providing irrigation water to vast areas of Telangana and Andhra Pradesh, significantly boosting the region's agriculture. The submerged area also contained ancient Buddhist relics, which were excavated and relocated to an island museum named Nagarjunakonda.", te: "నాగార్జున సాగర్ డ్యామ్ కృష్ణా నదిపై నిర్మించిన ఒక స్మారక రాతి ఆనకట్ట. ఇది స్వతంత్ర భారతదేశం యొక్క తొలి భారీ-స్థాయి మౌలిక సదుపాయాల ప్రాజెక్టులలో ఒకటి, 1955లో ప్రారంభించబడి 1967 నాటికి పూర్తయింది. ఈ డ్యామ్ ఒక భారీ జలాశయాన్ని, నాగార్జున సాగర్‌ను సృష్టించింది, ఇది ప్రపంచంలో మూడవ అతిపెద్ద మానవ నిర్మిత సరస్సు. ఈ ప్రాజెక్ట్ తెలంగాణ మరియు ఆంధ్రప్రదేశ్‌లోని విస్తారమైన ప్రాంతాలకు నీటిపారుదల నీటిని అందించడంలో కీలక పాత్ర పోషించింది, ఈ ప్రాంత వ్యవసాయాన్ని గణనీయంగా పెంచింది. మునిగిపోయిన ప్రాంతంలో పురాతన బౌద్ధ అవశేషాలు కూడా ఉన్నాయి, అవి తవ్వకం చేయబడి నాగార్జునకొండ అనే ద్వీప మ్యూజియంకు తరలించబడ్డాయి." },
    bestTimeToVisit: { en: "August to February, when the dam gates are often open.", te: "ఆగస్టు నుండి ఫిబ్రవరి వరకు, డ్యామ్ గేట్లు తరచుగా తెరిచి ఉంటాయి." },
    localCuisine: { en: "Local Telangana food, fresh fish from the reservoir.", te: "స్థానిక తెలంగాణ ఆహారం, జలాశయం నుండి తాజా చేపలు." },
    culturalEvents: { en: "Boating to Nagarjunakonda island, which houses a Buddhist museum.", te: "బౌద్ధ మ్యూజియం ఉన్న నాగార్జునకొండ ద్వీపానికి బోటింగ్." },
    distanceFromHyderabad: "Approx. 165 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "dam reservoir" }, { url: "https://placehold.co/400x300.png", hint: "dam gates" }],
    type: 'telangana',
  },
  {
    id: "pochampally",
    slug: "pochampally",
    name: { en: "Pochampally", te: "పోచంపల్లి" },
    description: { en: "A town famous for its traditional Ikat sarees, recognized as a World Craft Village.", te: "ప్రపంచ క్రాఫ్ట్ విలేజ్‌గా గుర్తింపు పొందిన, దాని సాంప్రదాయ ఇక్కత్ చీరలకు ప్రసిద్ధి చెందిన పట్టణం." },
    image: "https://images.unsplash.com/photo-1695150110878-a76e59db0b90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxwb2NoYW1wYWxseSUyMHZpbGxhZ2V8ZW58MHx8fHwxNzUzNjA0MTg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "textile weaving",
    regionTags: ["Telangana", "Yadadri Bhuvanagiri"],
    historicalSignificance: { en: "Pochampally is globally renowned for its unique style of silk and cotton sarees, woven using the Ikat technique. This traditional craft involves dyeing the threads before weaving to create intricate geometric patterns. The skill has been passed down through generations. Historically, Pochampally also holds significance as the place where the Bhoodan Movement (Land Gift Movement) was launched by Acharya Vinoba Bhave in 1951, which aimed to persuade wealthy landowners to voluntarily donate a percentage of their land to the landless.", te: "పోచంపల్లి ఇక్కత్ టెక్నిక్‌ను ఉపయోగించి నేసిన దాని ప్రత్యేకమైన పట్టు మరియు కాటన్ చీరల శైలికి ప్రపంచవ్యాప్తంగా ప్రసిద్ధి చెందింది. ఈ సాంప్రదాయ కళలో క్లిష్టమైన జ్యామితీయ నమూనాలను సృష్టించడానికి నేయడానికి ముందు దారాలకు రంగు వేయడం ఉంటుంది. ఈ నైపుణ్యం తరతరాలుగా వస్తోంది. చారిత్రాత్మకంగా, పోచంపల్లి భూదాన్ ఉద్యమం (భూమి బహుమతి ఉద్యమం) 1951లో ఆచార్య వినోబా భావేచే ప్రారంభించబడిన ప్రదేశంగా కూడా ప్రాముఖ్యతను కలిగి ఉంది, ఇది ధనిక భూస్వాములను స్వచ్ఛందంగా వారి భూమిలో కొంత శాతాన్ని భూమిలేని వారికి దానం చేయడానికి ఒప్పించడం లక్ష్యంగా పెట్టుకుంది." },
    bestTimeToVisit: { en: "Throughout the year.", te: "ఏడాది పొడవునా." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Visitors can observe the weaving process and purchase handcrafted textiles.", te: "సందర్శకులు నేత ప్రక్రియను గమనించవచ్చు మరియు చేతితో తయారు చేసిన వస్త్రాలను కొనుగోలు చేయవచ్చు." },
    distanceFromHyderabad: "Approx. 40 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ikat saree" }, { url: "https://placehold.co/400x300.png", hint: "handloom weaver" }],
    type: 'telangana',
  },
  {
    id: "manjira-wildlife-sanctuary",
    slug: "manjira-wildlife-sanctuary",
    name: { en: "Manjira Wildlife Sanctuary", te: "మంజీరా వన్యప్రాణుల అభయారణ్యం" },
    description: { en: "A riverine sanctuary that is home to a large population of mugger crocodiles and various bird species.", te: "మగ్గర్ మొసళ్ళు మరియు వివిధ పక్షి జాతులకు నిలయంగా ఉన్న ఒక నదీతీర అభయారణ్యం." },
    image: "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx3aWxkbGlmZXxlbnwwfHx8fDE3NTM2MDQzNDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "wildlife sanctuary",
    regionTags: ["Telangana", "Sangareddy"],
    historicalSignificance: { en: "This sanctuary is located along the Manjira River. It was originally established in 1978 as a crocodile sanctuary to protect the vulnerable mugger crocodile population. The sanctuary now consists of nine small islands and has become a thriving habitat for a variety of resident and migratory birds, making it a popular destination for birdwatchers. The dense vegetation and the reservoir create a unique ecosystem that supports this biodiversity.", te: "ఈ అభయారణ్యం మంజీరా నది వెంబడి ఉంది. ఇది వాస్తవానికి 1978లో అసురక్షిత మగ్గర్ మొసలి జనాభాను రక్షించడానికి ఒక మొసళ్ళ అభయారణ్యంగా స్థాపించబడింది. ఈ అభయారణ్యం ఇప్పుడు తొమ్మిది చిన్న ద్వీపాలను కలిగి ఉంది మరియు వివిధ నివాస మరియు వలస పక్షులకు ఒక అభివృద్ధి చెందుతున్న నివాసంగా మారింది, ఇది పక్షి వీక్షకులకు ఒక ప్రసిద్ధ గమ్యస్థానంగా మారింది. దట్టమైన వృక్షసంపద మరియు జలాశయం ఈ జీవవైవిధ్యానికి మద్దతు ఇచ్చే ఒక ప్రత్యేకమైన పర్యావరణ వ్యవస్థను సృష్టిస్తాయి." },
    bestTimeToVisit: { en: "November to March, for bird watching.", te: "నవంబర్ నుండి మార్చి వరకు, పక్షులను చూడటానికి." },
    localCuisine: { en: "Not applicable within the sanctuary.", te: "అభయారణ్యం లోపల వర్తించదు." },
    culturalEvents: { en: "Boating and bird watching tours.", te: "బోటింగ్ మరియు పక్షులను చూసే పర్యటనలు." },
    distanceFromHyderabad: "Approx. 50 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "mugger crocodile" }, { url: "https://placehold.co/400x300.png", hint: "migratory birds" }],
    type: 'telangana',
  },
  {
    id: "bhongir-fort",
    slug: "bhongir-fort",
    name: { en: "Bhongir Fort", te: "భువనగిరి కోట" },
    description: { en: "A massive fort built on a monolithic rock by the Western Chalukya king Tribhuvanamalla Vikramaditya VI.", te: "పశ్చిమ చాళుక్య రాజు త్రిభువనమల్ల విక్రమాదిత్య VI చే ఒకే రాతిపై నిర్మించబడిన ఒక భారీ కోట." },
    image: "https://images.unsplash.com/photo-1706103780703-d044f10c30a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOHx8QmhvbmdpciUyMGZvcnR8ZW58MHx8fHwxNzUzNjA0MzczfDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "hill fort",
    regionTags: ["Telangana", "Yadadri Bhuvanagiri"],
    historicalSignificance: { en: "Bhongir Fort was built in the 10th century on a unique, egg-shaped monolithic rock. It was constructed by the Western Chalukya ruler Tribhuvanamalla Vikramaditya VI and was named Tribhuvanagiri. The fort was later ceded to the Kakatiya dynasty and played a significant role in their kingdom. The fort's defenses were considered impregnable due to the steep climb and the massive rock. Today, the ruins of the fort offer a challenging trek and panoramic views of the surrounding landscape.", te: "భువనగిరి కోట 10వ శతాబ్దంలో ఒక ప్రత్యేకమైన, గుడ్డు ఆకారపు ఏకశిలా రాయిపై నిర్మించబడింది. ఇది పశ్చిమ చాళుక్య పాలకుడు త్రిభువనమల్ల విక్రమాదిత్య VI చే నిర్మించబడింది మరియు దీనికి త్రిభువనగిరి అని పేరు పెట్టారు. ఈ కోట తరువాత కాకతీయ రాజవంశానికి అప్పగించబడింది మరియు వారి రాజ్యంలో ఒక ముఖ్యమైన పాత్ర పోషించింది. నిటారుగా ఎక్కడం మరియు భారీ రాయి కారణంగా కోట యొక్క రక్షణలు అభేద్యమైనవిగా పరిగణించబడ్డాయి. నేడు, కోట యొక్క శిధిలాలు ఒక సవాలుతో కూడిన ట్రెక్‌ను మరియు పరిసర ప్రకృతి దృశ్యం యొక్క విస్తృత దృశ్యాలను అందిస్తాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Local eateries in Bhongir town.", te: "భువనగిరి పట్టణంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A popular destination for trekking and rock climbing.", te: "ట్రెక్కింగ్ మరియు రాక్ క్లైంబింగ్‌కు ఒక ప్రసిద్ధ గమ్యస్థానం." },
    distanceFromHyderabad: "Approx. 50 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "rock fortress" }, { url: "https://placehold.co/400x300.png", hint: "fort viewpoint" }],
    type: 'telangana',
  },
  {
    id: "medak-cathedral",
    slug: "medak-cathedral",
    name: { en: "Medak Cathedral", te: "మెదక్ కెథెడ్రల్" },
    description: { en: "One of the largest dioceses in Asia and the second-largest church in the world after the Vatican.", te: "ఆసియాలో అతిపెద్ద డయోసీస్‌లలో ఒకటి మరియు వాటికన్ తర్వాత ప్రపంచంలో రెండవ అతిపెద్ద చర్చి." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "large church",
    regionTags: ["Telangana", "Medak"],
    historicalSignificance: { en: "The Medak Cathedral stands as a testament to Gothic Revival architecture in India. Its construction was started in 1914 by Charles Walker Posnett of the British Wesleyan Methodists and took a decade to complete. The church was built during a period of famine in the region, and its construction provided work for the affected people. The cathedral's most stunning features are its massive size and the magnificent stained-glass windows, which depict different scenes from the life of Jesus Christ. These windows were designed and installed at different times, creating a beautiful narrative art piece.", te: "మెదక్ కెథెడ్రల్ భారతదేశంలో గోతిక్ రివైవల్ వాస్తుశిల్పానికి ఒక నిదర్శనంగా నిలుస్తుంది. దీని నిర్మాణం 1914లో బ్రిటిష్ వెస్లియన్ మెథడిస్ట్‌లకు చెందిన చార్లెస్ వాకర్ పోస్నెట్ చే ప్రారంభించబడింది మరియు పూర్తి చేయడానికి ఒక దశాబ్దం పట్టింది. ఈ ప్రాంతంలో కరువు కాలంలో ఈ చర్చి నిర్మించబడింది, మరియు దాని నిర్మాణం ప్రభావిత ప్రజలకు పనిని అందించింది. కెథెడ్రల్ యొక్క అత్యంత అద్భుతమైన లక్షణాలు దాని భారీ పరిమాణం మరియు యేసుక్రీస్తు జీవితంలోని విభిన్న దృశ్యాలను వర్ణించే అద్భుతమైన స్టెయిన్డ్-గ్లాస్ కిటికీలు. ఈ కిటికీలు వేర్వేరు సమయాల్లో రూపొందించబడ్డాయి మరియు நிறுவப்பட்டன, ఇది ఒక అందమైన కథన కళాఖండాన్ని సృష్టించింది." },
    bestTimeToVisit: { en: "Throughout the year, especially during Christmas.", te: "ఏడాది పొడవునా, ముఖ్యంగా క్రిస్మస్ సమయంలో." },
    localCuisine: { en: "Local food in Medak town.", te: "మెదక్ పట్టణంలో స్థానిక ఆహారం." },
    culturalEvents: { en: "Christmas celebrations are grand and attract many visitors.", te: "క్రిస్మస్ వేడుకలు ఘనంగా ఉంటాయి మరియు చాలా మంది సందర్శకులను ఆకర్షిస్తాయి." },
    distanceFromHyderabad: "Approx. 95 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "stained glass" }, { url: "https://placehold.co/400x300.png", hint: "church interior" }],
    type: 'telangana',
  },
  {
    id: "thousand-pillar-temple",
    slug: "thousand-pillar-temple",
    name: { en: "Thousand Pillar Temple", te: "వెయ్యి స్తంభాల గుడి" },
    description: { en: "A star-shaped temple renowned for its Kakatiyan architecture.", te: "కాకతీయ వాస్తుశిల్పానికి ప్రసిద్ధి చెందిన నక్షత్రాకార ఆలయం." },
    image: "https://images.unsplash.com/photo-1660463835177-bc6329055a6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxUaG91c2FuZCUyMHBpbGxhciUyMHRlbXBsZXxlbnwwfHx8fDE3NTM2MDQ0MTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "pillar temple",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "One of the finest examples of Kakatiya architecture, the Thousand Pillar Temple was built in 1163 AD by King Rudra Deva. The temple is built in a unique star-shaped, triple-shrined (Trikutalayam) design, with shrines dedicated to Lord Shiva, Vishnu, and Surya. The temple is famous for its richly carved pillars, intricate sculptures, and a large monolithic Nandi (bull statue). The pillars are arranged in such a way that they do not obstruct the view of the deity from any angle in the temple.", te: "కాకతీయ వాస్తుశిల్పం యొక్క ఉత్తమ ఉదాహరణలలో ఒకటైన వెయ్యి స్తంభాల గుడి, క్రీ.శ. 1163లో రాజు రుద్ర దేవునిచే నిర్మించబడింది. ఈ ఆలయం ఒక ప్రత్యేకమైన నక్షత్రాకార, త్రికుటాలయం నమూనాలో నిర్మించబడింది, ఇందులో శివుడు, విష్ణువు మరియు సూర్యునికి అంకితం చేయబడిన గర్భగుడులు ఉన్నాయి. ఈ ఆలయం దాని గొప్పగా చెక్కబడిన స్తంభాలు, క్లిష్టమైన శిల్పాలు మరియు ఒక పెద్ద ఏకశిలా నంది (ఎద్దు విగ్రహం)కి ప్రసిద్ధి చెందింది. ఈ స్తంభాలు ఆలయంలో ఏ కోణం నుండి అయినా దైవ దర్శనానికి అడ్డు రాకుండా అమర్చబడి ఉంటాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Warangal specialties.", te: "వరంగల్ ప్రత్యేకతలు." },
    culturalEvents: { en: "Maha Shivaratri is celebrated with great pomp.", te: "మహా శివరాత్రిని అత్యంత వైభవంగా జరుపుకుంటారు." },
    distanceFromHyderabad: "Approx. 150 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple carving" }, { url: "https://placehold.co/400x300.png", hint: "temple nandi" }],
    type: 'telangana',
  },
   {
    id: "birla-mandir",
    slug: "birla-mandir",
    name: { en: "Birla Mandir", te: "బిర్లా మందిర్" },
    description: { en: "A magnificent Hindu temple dedicated to Lord Venkateswara, built entirely of white marble.", te: "పూర్తిగా తెల్లని పాలరాతితో నిర్మించబడిన, శ్రీ వెంకటేశ్వర స్వామికి అంకితం చేయబడిన ఒక అద్భుతమైన హిందూ దేవాలయం." },
    image: "https://images.unsplash.com/photo-1701783470382-19eaea147ca7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxCaXJsYSUyMG1hbmRpcnxlbnwwfHx8fDE3NTM2MDQ0NDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "birla mandir",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Perched atop the Naubat Pahad hillock, the Birla Mandir in Hyderabad is a modern architectural marvel. Constructed in 1976 by the industrialist Birla family, it is built from 2000 tons of pure white marble sourced from Rajasthan. The temple's architecture is a blend of South Indian (Dravidian) and North Indian (Nagasara) styles. It is primarily dedicated to Lord Venkateswara, but also features shrines for other deities. The serene atmosphere and the panoramic view of the city it offers make it a popular destination for both pilgrims and tourists.", te: "నౌబత్ పహాడ్ కొండపై ఉన్న హైదరాబాద్‌లోని బిర్లా మందిర్ ఒక ఆధునిక వాస్తుశిల్ప అద్భుతం. 1976లో పారిశ్రామికవేత్త బిర్లా కుటుంబంచే నిర్మించబడిన ఇది, రాజస్థాన్ నుండి తెచ్చిన 2000 టన్నుల స్వచ్ఛమైన తెల్లని పాలరాతితో నిర్మించబడింది. ఆలయ వాస్తుశిల్పం దక్షిణ భారత (ద్రావిడ) మరియు ఉత్తర భారత (నాగసర) శైలుల మిశ్రమం. ఇది ప్రధానంగా శ్రీ వెంకటేశ్వర స్వామికి అంకితం చేయబడింది, కానీ ఇతర దేవతలకు కూడా గర్భగుడులను కలిగి ఉంది. ఇది అందించే ప్రశాంతమైన వాతావరణం మరియు నగరం యొక్క విస్తృత దృశ్యం దీనిని యాత్రికులు మరియు పర్యాటకులకు ఒక ప్రసిద్ధ గమ్యస్థానంగా చేస్తాయి." },
    bestTimeToVisit: { en: "Throughout the year, especially serene in the evenings.", te: "ఏడాది పొడవునా, ముఖ్యంగా సాయంత్రం వేళల్లో ప్రశాంతంగా ఉంటుంది." },
    localCuisine: { en: "Various restaurants are available in the vicinity.", te: "సమీపంలో వివిధ రెస్టారెంట్లు అందుబాటులో ఉన్నాయి." },
    culturalEvents: { en: "Major Hindu festivals like Janmashtami and Diwali are celebrated grandly.", te: "జన్మాష్టమి మరియు దీపావళి వంటి ప్రధాన హిందూ పండుగలను వైభవంగా జరుపుకుంటారు." },
    distanceFromHyderabad: "Located within Hyderabad city.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple marble" }, { url: "https://placehold.co/400x300.png", hint: "hyderabad skyline" }],
    type: 'telangana',
  },
  {
    id: "swarnagiri-temple",
    slug: "swarnagiri-temple",
    name: { en: "Swarnagiri Temple", te: "స్వర్ణగిరి దేవాలయం" },
    description: { en: "A recently constructed temple complex with impressive gopurams and architecture.", te: "ఆకట్టుకునే గోపురాలు మరియు వాస్తుశిల్పంతో ఇటీవల నిర్మించిన ఆలయ సముదాయం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "swarnagiri temple",
    regionTags: ["Telangana"],
    historicalSignificance: { en: "Swarnagiri Temple is a modern pilgrimage center built in the traditional South Indian architectural style. While not ancient, it has quickly gained prominence due to its magnificent structure, towering gopurams (temple towers), and intricate carvings. The temple is dedicated to Lord Venkateswara and is situated atop a hill, offering serene and panoramic views of the surroundings. Its construction represents a continuation of traditional temple-building arts and crafts in the modern era.", te: "స్వర్ణగిరి దేవాలయం సాంప్రదాయ దక్షిణ భారత వాస్తుశిల్పంలో నిర్మించిన ఒక ఆధునిక పుణ్యక్షేత్రం. ఇది పురాతనమైనది కానప్పటికీ, దాని అద్భుతమైన నిర్మాణం, ఎత్తైన గోపురాలు (ఆలయ గోపురాలు), మరియు క్లిష్టమైన శిల్పాల కారణంగా ఇది త్వరగా ప్రాముఖ్యతను పొందింది. ఈ ఆలయం శ్రీ వెంకటేశ్వర స్వామికి అంకితం చేయబడింది మరియు ఒక కొండపై ఉంది, పరిసరాల యొక్క ప్రశాంతమైన మరియు విస్తృత దృశ్యాలను అందిస్తుంది. దాని నిర్మాణం ఆధునిక యుగంలో సాంప్రదాయ ఆలయ నిర్మాణ కళలు మరియు చేతిపనుల కొనసాగింపును సూచిస్తుంది." },
    bestTimeToVisit: { en: "October to February.", te: "అక్టోబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Temple prasadam and nearby local eateries.", te: "ఆలయ ప్రసాదం మరియు సమీపంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "Major temple festivals and religious ceremonies.", te: "ప్రధాన ఆలయ ఉత్సవాలు మరియు మతపరమైన కార్యక్రమాలు." },
    distanceFromHyderabad: "Approx. 100 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple gopuram" }, { url: "https://placehold.co/400x300.png", hint: "temple sculpture" }],
    type: 'telangana',
  },
  {
    id: "suryapet",
    slug: "suryapet",
    name: { en: "Suryapet", te: "సూర్యాపేట" },
    description: { en: "Known as the 'Gateway of Telangana', it is a region with historical temples and sites.", te: "'తెలంగాణ ముఖద్వారం'గా పిలువబడే ఇది, చారిత్రక దేవాలయాలు మరియు ప్రదేశాలు ఉన్న ప్రాంతం." },
    image: "https://images.unsplash.com/photo-1723005618130-ad8c79bb4c97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxzdXJ5YXBldHxlbnwwfHx8fDE3NTM2MDQ4NjV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "historic town",
    regionTags: ["Telangana", "Suryapet"],
    historicalSignificance: { en: "Suryapet has a rich and layered history, with archaeological evidence suggesting human habitation since the Neolithic and Megalithic periods. Historically, it was part of the realms of various powerful dynasties, including the Kakatiyas, Bahmanis, and later the Nizams of Hyderabad. The region is dotted with several ancient temples and historical sites that reflect its past glory and cultural evolution over the centuries. Its strategic location also made it an important center for trade and administration.", te: "సూర్యాపేటకు గొప్ప మరియు పొరలు పొరలుగా ఉన్న చరిత్ర ఉంది, పురావస్తు ఆధారాలు నవీన శిలా మరియు బృహత్ శిలా యుగాల నుండి మానవ నివాసాలను సూచిస్తున్నాయి. చారిత్రాత్మకంగా, ఇది కాకతీయులు, బహమనీలు, మరియు తరువాత హైదరాబాద్ నిజాంలతో సహా వివిధ శక్తివంతమైన రాజవంశాల రాజ్యాలలో భాగంగా ఉండేది. ఈ ప్రాంతం శతాబ్దాలుగా దాని గత వైభవాన్ని మరియు సాంస్కృతిక పరిణామాన్ని ప్రతిబింబించే అనేక పురాతన దేవాలయాలు మరియు చారిత్రక ప్రదేశాలతో నిండి ఉంది. దాని వ్యూహాత్మక స్థానం కూడా దీనిని వాణిజ్యం మరియు పరిపాలనకు ఒక ముఖ్యమైన కేంద్రంగా చేసింది." },
    bestTimeToVisit: { en: "October to February.", te: "అక్టోబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Various local jatras and festivals are celebrated throughout the year.", te: "ఏడాది పొడవునా వివిధ స్థానిక జాతరలు మరియు పండుగలు జరుపుకుంటారు." },
    distanceFromHyderabad: "Approx. 135 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ancient temple" }, { url: "https://placehold.co/400x300.png", hint: "rural landscape" }],
    type: 'telangana',
  }
];

export const indiaDestinations: Destination[] = [
  {
    id: "taj-mahal",
    slug: "taj-mahal",
    name: { en: "Taj Mahal", te: "తాజ్ మహల్" },
    description: { en: "An ivory-white marble mausoleum on the south bank of the Yamuna river in Agra.", te: "ఆగ్రాలోని యమునా నది దక్షిణ ఒడ్డున ఉన్న ఒక దంతపు-తెలుపు పాలరాతి సమాధి." },
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxUYWolMjBNYWhhbHxlbnwwfHx8fDE3NTM2MDQ5NzV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "taj mahal",
    regionTags: ["India", "Agra"],
    historicalSignificance: { en: "The Taj Mahal is an immense mausoleum of ivory-white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife, Mumtaz Mahal. It is the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage. The complex, a UNESCO World Heritage site, also includes a mosque, a guest house, and formal gardens, all set within a walled enclosure.", te: "తాజ్ మహల్ ఒక అపారమైన దంతపు-తెలుపు పాలరాతి సమాధి, ఇది ఆగ్రాలో 1631 మరియు 1648 మధ్య మొఘల్ చక్రవర్తి షాజహాన్ ఆదేశానుసారం అతని అభిమాన భార్య ముంతాజ్ మహల్ జ్ఞాపకార్థం నిర్మించబడింది. ఇది భారతదేశంలో ముస్లిం కళ యొక్క ఆభరణం మరియు ప్రపంచ వారసత్వం యొక్క సార్వత్రిక ప్రశంసలు పొందిన కళాఖండాలలో ఒకటి. యునెస్కో ప్రపంచ వారసత్వ ప్రదేశమైన ఈ సముదాయంలో ఒక మసీదు, ఒక అతిథి గృహం, మరియు అధికారిక ఉద్యానవనాలు కూడా ఉన్నాయి, అన్నీ ఒక గోడల ఆవరణలో ఉన్నాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Petha, Mughlai cuisine.", te: "పేఠా, ముఘలాయ్ వంటకాలు." },
    culturalEvents: { en: "Taj Mahotsav in February.", te: "ఫిబ్రవరిలో తాజ్ మహోత్సవ్." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "mausoleum detail" }, { url: "https://placehold.co/400x300.png", hint: "yamuna river" }],
    type: 'india',
  },
  {
    id: "jaipur-city-palace",
    slug: "jaipur-city-palace",
    name: { en: "Jaipur City Palace", te: "జైపూర్ సిటీ ప్యాలెస్" },
    description: { en: "A palace complex in Jaipur, the capital of the Rajasthan state.", te: "రాజస్థాన్ రాష్ట్ర రాజధాని జైపూర్‌లోని ఒక రాజభవన సముదాయం." },
    image: "https://images.unsplash.com/photo-1701087366618-112f1b333a9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxKYWlwdXIlMjBjaXR5JTIwcGFsYWNlfGVufDB8fHx8MTc1MzYwNTAzMHww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "jaipur palace",
    regionTags: ["India", "Jaipur"],
    historicalSignificance: { en: "The City Palace of Jaipur was established at the same time as the city itself, by Maharaja Sawai Jai Singh II in 1727. It was the seat of the Maharaja of Jaipur, the head of the Kachwaha Rajput clan. The palace is a stunning blend of Rajput and Mughal architectural styles, featuring vast courtyards, gardens, and buildings. Part of the complex is still a royal residence, while other areas have been converted into museums showcasing royal costumes, weaponry, and art.", te: "జైపూర్ సిటీ ప్యాలెస్, జైపూర్ నగరం స్థాపించబడిన అదే సమయంలో 1727లో మహారాజా సవాయ్ జై సింగ్ II చే స్థాపించబడింది. ఇది కచ్వాహ రాజపుత్ర వంశం యొక్క అధిపతి అయిన జైపూర్ మహారాజా యొక్క స్థానం. ఈ ప్యాలెస్ రాజపుత్ర మరియు మొఘల్ వాస్తుశిల్పాల యొక్క అద్భుతమైన మిశ్రమం, ఇందులో విశాలమైన ప్రాంగణాలు, ఉద్యానవనాలు, మరియు భవనాలు ఉన్నాయి. సముదాయంలో కొంత భాగం ఇప్పటికీ రాజ నివాసంగా ఉంది, ఇతర ప్రాంతాలు రాజ దుస్తులు, ఆయుధాలు, మరియు కళను ప్రదర్శించే మ్యూజియంలుగా మార్చబడ్డాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Dal Baati Churma, Ghewar.", te: "దాల్ బాటీ చుర్మా, ఘేవర్." },
    culturalEvents: { en: "Gangaur festival, Teej festival.", te: "గంగౌర్ పండుగ, తీజ్ పండుగ." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "palace courtyard" }, { url: "https://placehold.co/400x300.png", hint: "palace gates" }],
    type: 'india',
  },
  {
    id: "varanasi-ghats",
    slug: "varanasi-ghats",
    name: { en: "Varanasi Ghats", te: "వారణాసి ఘాట్లు" },
    description: { en: "Riverfront steps leading to the banks of the River Ganges.", te: "గంగా నది ఒడ్డుకు దారితీసే నదీతీర మెట్లు." },
    image: "https://images.unsplash.com/photo-1706186839147-0d708602587b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx2YXJhbmFzaSUyMGdoYXRzfGVufDB8fHx8MTc1MzYwNTA2MHww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "varanasi ghats",
    regionTags: ["India", "Varanasi"],
    historicalSignificance: { en: "Varanasi, one of the oldest living cities in the world, is famous for its numerous ghats—steps leading down to the River Ganges. These ghats have been central to the city's religious life for centuries. Most were built after 1700 AD under the patronage of Maratha rulers. They serve both mundane and sacred purposes, from daily bathing and laundry to complex religious ceremonies and cremations. The Dashashwamedh Ghat is famous for its spectacular evening Ganga Aarti ceremony.", te: "ప్రపంచంలోని అత్యంత పురాతన జీవన నగరాలలో ఒకటైన వారణాసి, గంగా నదికి దారితీసే దాని అనేక ఘాట్లకు ప్రసిద్ధి. ఈ ఘాట్లు శతాబ్దాలుగా నగరం యొక్క మత జీవితానికి కేంద్రంగా ఉన్నాయి. చాలా వరకు 1700 AD తర్వాత మరాఠా పాలకుల ప్రోత్సాహంతో నిర్మించబడ్డాయి. అవి రోజువారీ స్నానం మరియు లాండ్రీ నుండి సంక్లిష్టమైన మతపరమైన వేడుకలు మరియు దహన సంస్కారాల వరకు లౌకిక మరియు పవిత్రమైన ప్రయోజనాలను అందిస్తాయి. దశాశ్వమేధ ఘాట్ దాని అద్భుతమైన సాయంత్రం గంగా హారతి వేడుకకు ప్రసిద్ధి చెందింది." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Kachori Sabzi, Lassi, Chaat.", te: "కచోరీ సబ్జీ, లస్సీ, చాట్." },
    culturalEvents: { en: "Ganga Aarti every evening, Dev Deepawali.", te: "ప్రతి సాయంత్రం గంగా హారతి, దేవ్ దీపావళి." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ganga aarti" }, { url: "https://placehold.co/400x300.png", hint: "river boats" }],
    type: 'india',
  },
   {
    id: "goa-beaches",
    slug: "goa-beaches",
    name: { en: "Goa Beaches", te: "గోవా బీచ్‌లు" },
    description: { en: "Famous for its stunning coastline, vibrant nightlife, and Portuguese heritage.", te: "దాని అద్భుతమైన తీరప్రాంతం, ఉత్సాహభరితమైన రాత్రి జీవితం మరియు పోర్చుగీస్ వారసత్వానికి ప్రసిద్ధి." },
    image: "https://images.unsplash.com/photo-1582972236019-ea4af5ffe587?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxHb2ElMjBiZWFjaHxlbnwwfHx8fDE3NTM2MDUwNzZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "goa beach",
    regionTags: ["India", "Goa"],
    historicalSignificance: { en: "Goa has a long history stretching back to the 3rd century BC. However, its modern identity was shaped by over 450 years of Portuguese rule, which began in the early 16th century. This long colonial period left a lasting legacy on Goa's culture, architecture, and cuisine. The churches and convents of Old Goa are a UNESCO World Heritage Site. Goa was liberated from Portuguese rule and became part of India in 1961. Today, its stunning beaches and unique culture make it a major global tourist destination.", te: "గోవాకు క్రీ.పూ. 3వ శతాబ్దానికి చెందిన సుదీర్ఘ చరిత్ర ఉంది. అయినప్పటికీ, దాని ఆధునిక గుర్తింపు 16వ శతాబ్దం ప్రారంభంలో ప్రారంభమైన 450 సంవత్సరాలకు పైగా పోర్చుగీస్ పాలనచే రూపొందించబడింది. ఈ సుదీర్ఘ వలసవాద కాలం గోవా సంస్కృతి, వాస్తుశిల్పం, మరియు వంటకాలపై శాశ్వత వారసత్వాన్ని వదిలివేసింది. పాత గోవా యొక్క చర్చిలు మరియు కాన్వెంట్లు యునెస్కో ప్రపంచ వారసత్వ ప్రదేశం. గోవా పోర్చుగీస్ పాలన నుండి విముక్తి పొంది 1961లో భారతదేశంలో భాగమైంది. నేడు, దాని అద్భుతమైన బీచ్‌లు మరియు ప్రత్యేకమైన సంస్కృతి దీనిని ఒక ప్రధాన ప్రపంచ పర్యాటక గమ్యస్థానంగా చేస్తాయి." },
    bestTimeToVisit: { en: "November to February.", te: "నవంబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Seafood, Vindaloo, Bebinca.", te: "సముద్రపు ఆహారం, విందాలూ, బెబింకా." },
    culturalEvents: { en: "Goa Carnival, Sunburn Festival.", te: "గోవా కార్నివాల్, సన్‌బర్న్ ఫెస్టివాల్." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "beach sunset" }, { url: "https://placehold.co/400x300.png", hint: "goa church" }],
    type: 'india',
  }
];

export const allDestinations = [...telanganaDestinations, ...indiaDestinations];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return allDestinations.find((dest) => dest.slug === slug);
}
