export type Language = 'en' | 'te';

export type TranslatedText = {
  [key in Language]: string;
};

export interface Destination {
  id: string;
  slug: string;
  name: TranslatedText;
  description: TranslatedText;
  image: string;
  dataAiHint: string;
  regionTags: string[];
  historicalSignificance: TranslatedText;
  bestTimeToVisit: TranslatedText;
  localCuisine: TranslatedText;
  culturalEvents: TranslatedText;
  distanceFromHyderabad: string | null;
  extraImages: { url: string, hint: string }[];
  type: 'telangana' | 'india';
}

export const telanganaDestinations: Destination[] = [
  {
    id: "charminar",
    slug: "charminar",
    name: { en: "Charminar", te: "చార్మినార్" },
    description: { en: "A historic monument and mosque in Hyderabad, an icon of the city.", te: "హైదరాబాద్‌లోని ఒక చారిత్రాత్మక స్మారక చిహ్నం మరియు మసీదు, నగరానికి ఒక చిహ్నం." },
    image: "https://images.unsplash.com/photo-1441911645956-df6e9bbc5496?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjaGFybWluYXJ8ZW58MHx8fHwxNzUzNTQ4MDU1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "charminar hyderabad",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Built in 1591 by Muhammad Quli Qutb Shah, it is a symbol of Hyderabad's rich past.", te: "1591లో ముహమ్మద్ కులీ కుతుబ్ షాచే నిర్మించబడినది, ఇది హైదరాబాద్ యొక్క గొప్ప గతానికి చిహ్నం." },
    bestTimeToVisit: { en: "October to March, to avoid the heat.", te: "వేడిని నివారించడానికి అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Hyderabadi Biryani, Haleem, Irani Chai.", te: "హైదరాబాదీ బిర్యానీ, హలీమ్, ఇరానీ చాయ్." },
    culturalEvents: { en: "Ramadan festivities, various cultural festivals.", te: "రంజాన్ ఉత్సవాలు, వివిధ సాంస్కృతిక పండుగలు." },
    distanceFromHyderabad: "Located in the heart of Hyderabad city.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "charminar architecture" }, { url: "https://placehold.co/400x300.png", hint: "hyderabad market" }],
    type: 'telangana',
  },
  {
    id: "golconda-fort",
    slug: "golconda-fort",
    name: { en: "Golconda Fort", te: "గోల్కొండ కోట" },
    description: { en: "A magnificent fortress complex known for its acoustics and grandeur.", te: "ధ్వనిశాస్త్రం మరియు వైభవానికి ప్రసిద్ధి చెందిన అద్భుతమైన కోట సముదాయం." },
    image: "https://images.unsplash.com/photo-1575492534537-792e4e1b8bed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxGb3J0fGVufDB8fHx8MTc1MzYwMzU0NHww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "golconda fort",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Originally a mud fort, it was rebuilt by the Qutb Shahi dynasty and was a famous diamond market.", te: "వాస్తవానికి మట్టి కోట, ఇది కుతుబ్ షాహీ రాజవంశంచే పునర్నిర్మించబడింది మరియు ప్రసిద్ధ వజ్రాల మార్కెట్‌గా ఉంది." },
    bestTimeToVisit: { en: "September to March.", te: "సెప్టెంబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Pathar ka Gosht, Kebabs.", te: "పత్తర్ కా గోష్ట్, కబాబ్స్." },
    culturalEvents: { en: "Sound and Light Show in the evenings.", te: "సాయంత్రం సౌండ్ అండ్ లైట్ షో." },
    distanceFromHyderabad: "Approx. 11 km from Hyderabad city center.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "fortress walls" }, { url: "https://placehold.co/400x300.png", hint: "fort ruins" }],
    type: 'telangana',
  },
  {
    id: "husain-sagar-lake",
    slug: "husain-sagar-lake",
    name: { en: "Hussain Sagar Lake", te: "హుస్సేన్ సాగర్ సరస్సు" },
    description: { en: "A heart-shaped lake with a large monolithic statue of the a Buddha in its center.", te: "మధ్యలో గౌతమ బుద్ధుని పెద్ద ఏకశిలా విగ్రహంతో ఉన్న హృదయాకార సరస్సు." },
    image: "https://images.unsplash.com/photo-1712422813106-dfb845a8a7ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxIdXNzYWluJTIwU2FnYXIlMjBMYWtlfGVufDB8fHx8MTc1MzYwMzY0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "hussain sagar",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Built in 1563 by Ibrahim Quli Qutb Shah, it is an artificial lake fed by the River Musi.", te: "1563లో ఇబ్రహీం కులీ కుతుబ్ షాచే నిర్మించబడినది, ఇది మూసీ నది ద్వారా నీరు అందించబడే ఒక కృత్రిమ సరస్సు." },
    bestTimeToVisit: { en: "All year round, especially evenings.", te: "ఏడాది పొడవునా, ముఖ్యంగా సాయంత్రం వేళల్లో." },
    localCuisine: { en: "Street food around the lake, various restaurants nearby.", te: "సరస్సు చుట్టూ వీధి ఆహారం, సమీపంలోని వివిధ రెస్టారెంట్లు." },
    culturalEvents: { en: "Lumbini Park events, boating.", te: "లుంబిని పార్క్ కార్యక్రమాలు, బోటింగ్." },
    distanceFromHyderabad: "Located in the heart of Hyderabad.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "buddha statue" }, { url: "https://placehold.co/400x300.png", hint: "lake boating" }],
    type: 'telangana',
  },
  {
    id: "ramoji-film-city",
    slug: "ramoji-film-city",
    name: { en: "Ramoji Film City", te: "రామోజీ ఫిల్మ్ సిటీ" },
    description: { en: "The world's largest integrated film city and a popular tourism and recreation center.", te: "ప్రపంచంలోనే అతిపెద్ద ఇంటిగ్రేటెడ్ ఫిల్మ్ సిటీ మరియు ఒక ప్రసిద్ధ పర్యాటక మరియు వినోద కేంద్రం." },
    image: "https://images.unsplash.com/photo-1598610339755-6e4e24737a27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxSYW1vamklMjBmaWxtJTIwY2l0eXxlbnwwfHx8fDE3NTM1NDkyNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "film city",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Opened in 1996, it has been certified by Guinness World Records as the largest studio complex in the world.", te: "1996లో ప్రారంభించబడింది, ఇది ప్రపంచంలోనే అతిపెద్ద స్టూడియో కాంప్లెక్స్‌గా గిన్నిస్ వరల్డ్ రికార్డ్స్ ద్వారా ధృవీకరించబడింది." },
    bestTimeToVisit: { en: "Throughout the year.", te: "ఏడాది పొడవునా." },
    localCuisine: { en: "Multiple restaurants within the film city catering to various tastes.", te: "ఫిల్మ్ సిటీలో వివిధ రకాల అభిరుచులకు అనుగుణంగా బహుళ రెస్టారెంట్లు ఉన్నాయి." },
    culturalEvents: { en: "Live shows, stunt shows, and thematic events throughout the year.", te: "లైవ్ షోలు, స్టంట్ షోలు, మరియు ఏడాది పొడవునా థీమాటిక్ ఈవెంట్‌లు." },
    distanceFromHyderabad: "Approx. 30 km from Hyderabad.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "film set" }, { url: "https://placehold.co/400x300.png", hint: "amusement park" }],
    type: 'telangana',
  },
  {
    id: "qutb-shahi-tombs",
    slug: "qutb-shahi-tombs",
    name: { en: "Qutb Shahi Tombs", te: "కుతుబ్ షాహీ సమాధులు" },
    description: { en: "A complex of tombs and mosques built in memory of the rulers of the Qutb Shahi dynasty.", te: "కుతుబ్ షాహీ రాజవంశం యొక్క పాలకుల జ్ఞాపకార్థం నిర్మించిన సమాధులు మరియు మసీదుల సముదాయం." },
    image: "https://images.unsplash.com/photo-1644326792898-d7c455000679?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxUb21ic3xlbnwwfHx8fDE3NTM2MDM4NDh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "historic tombs",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "The tombs are a blend of Persian, Pashtun and Hindu architectural styles. There are 7 tombs in total.", te: "ఈ సమాధులు పెర్షియన్, పష్టున్ మరియు హిందూ వాస్తుశిల్పాల మిశ్రమం. మొత్తం 7 సమాధులు ఉన్నాయి." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Local eateries near Golconda Fort.", te: "గోల్కొండ కోట సమీపంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A place of historical interest and reflection.", te: "చారిత్రక ఆసక్తి మరియు ప్రతిబింబం యొక్క ప్రదేశం." },
    distanceFromHyderabad: "Approx. 12 km from Hyderabad city center.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "tomb architecture" }, { url: "https://placehold.co/400x300.png", hint: "tomb dome" }],
    type: 'telangana',
  },
  {
    id: "warangal-fort",
    slug: "warangal-fort",
    name: { en: "Warangal Fort", te: "వరంగల్ కోట" },
    description: { en: "An ancient fort known for its impressive stone gateways (Kakatiya Kala Thoranam).", te: "దాని ఆకట్టుకునే రాతి ముఖద్వారాలకు (కాకతీయ కళా తోరణం) ప్రసిద్ధి చెందిన ఒక పురాతన కోట." },
    image: "https://images.unsplash.com/photo-1690796943027-72efe121234a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxXYXJhbmdhbCUyMGZvcnR8ZW58MHx8fHwxNzUzNjAzODgxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "warangal fort",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "The fort was the capital of the Kakatiya dynasty. The architectural remnants are a testament to their skill.", te: "ఈ కోట కాకతీయ రాజవంశానికి రాజధానిగా ఉండేది. వాస్తుశిల్ప అవశేషాలు వారి నైపుణ్యానికి నిదర్శనం." },
    bestTimeToVisit: { en: "September to April.", te: "సెప్టెంబర్ నుండి ఏప్రిల్ వరకు." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Local festivals and jatras.", te: "స్థానిక పండుగలు మరియు జాతరలు." },
    distanceFromHyderabad: "Approx. 145 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "kakatiya thoranam" }, { url: "https://placehold.co/400x300.png", hint: "fort ruins" }],
    type: 'telangana',
  },
  {
    id: "kakatiya-kala-thoranam",
    slug: "kakatiya-kala-thoranam",
    name: { en: "Kakatiya Kala Thoranam", te: "కాకతీయ కళా తోరణం" },
    description: { en: "The iconic stone archway of Warangal Fort, a symbol of the Kakatiya dynasty and the emblem of Telangana.", te: "వరంగల్ కోట యొక్క ఐకానిక్ రాతి తోరణం, కాకతీయ రాజవంశం యొక్క చిహ్నం మరియు తెలంగాణ రాష్ట్ర చిహ్నం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "ancient archway",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "Built in the 12th century, these ornate arches are unique in South Indian architecture and show the grandeur of the Kakatiyas.", te: "12వ శతాబ్దంలో నిర్మించబడిన ఈ అలంకరించబడిన తోరణాలు దక్షిణ భారత వాస్తుశిల్పంలో ప్రత్యేకమైనవి మరియు కాకతీయుల వైభవాన్ని చూపుతాయి." },
    bestTimeToVisit: { en: "September to April.", te: "సెప్టెంబర్ నుండి ఏప్రిల్ వరకు." },
    localCuisine: { en: "Local Warangal cuisine.", te: "స్థానిక వరంగల్ వంటకాలు." },
    culturalEvents: { en: "Part of the Warangal Fort complex, a site of major historical significance.", te: "వరంగల్ కోట సముదాయంలో భాగం, ఇది ప్రధాన చారిత్రక ప్రాముఖ్యత కలిగిన ప్రదేశం." },
    distanceFromHyderabad: "Approx. 145 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "stone carving" }, { url: "https://placehold.co/400x300.png", hint: "archway detail" }],
    type: 'telangana',
  },
  {
    id: "pakhal-lake",
    slug: "pakhal-lake",
    name: { en: "Pakhal Lake", te: "పాకాల సరస్సు" },
    description: { en: "A man-made lake situated in the Pakhal Wildlife Sanctuary, surrounded by lush forests.", te: "పాకాల వన్యప్రాణుల అభయారణ్యంలో ఉన్న ఒక మానవ నిర్మిత సరస్సు, పచ్చని అడవులతో చుట్టుముట్టబడి ఉంది." },
    image: "https://images.unsplash.com/photo-1629378343801-abfbcaca500d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMnx8UGFraGFsJTIwTGFrZXxlbnwwfHx8fDE3NTM2MDM5Njd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "serene lake",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "Built by the Kakatiya king Ganapati Deva in 1213 AD, it's an example of ancient engineering.", te: "1213 ADలో కాకతీయ రాజు గణపతి దేవునిచే నిర్మించబడింది, ఇది ప్రాచీన ఇంజనీరింగ్‌కు ఒక ఉదాహరణ." },
    bestTimeToVisit: { en: "November to June, for pleasant weather and wildlife spotting.", te: "నవంబర్ నుండి జూన్ వరకు, ఆహ్లాదకరమైన వాతావరణం మరియు వన్యప్రాణులను చూడటానికి." },
    localCuisine: { en: "Local eateries in nearby towns.", te: "సమీప పట్టణాలలో స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A popular spot for picnics, boating, and nature walks.", te: "పిక్నిక్‌లు, బోటింగ్, మరియు ప్రకృతి నడకలకు ఒక ప్రసిద్ధ ప్రదేశం." },
    distanceFromHyderabad: "Approx. 200 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "wildlife sanctuary" }, { url: "https://placehold.co/400x300.png", hint: "forest lake" }],
    type: 'telangana',
  },
  {
    id: "nagarjuna-sagar-dam",
    slug: "nagarjuna-sagar-dam",
    name: { en: "Nagarjuna Sagar Dam", te: "నాగార్జున సాగర్ డ్యాం" },
    description: { en: "One of the world's largest and tallest masonry dams, built across the Krishna river.", te: "ప్రపంచంలోనే అతిపెద్ద మరియు ఎత్తైన రాతి ఆనకట్టలలో ఒకటి, కృష్ణా నదిపై నిర్మించబడింది." },
    image: "https://images.unsplash.com/photo-1612444944202-b8a424ca7663?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxOYWdhcmp1bmElMjBTYWdhciUyMGRhbXxlbnwwfHx8fDE3NTM2MDQwNjd8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "large dam",
    regionTags: ["Telangana", "Nalgonda"],
    historicalSignificance: { en: "A modern marvel of engineering, the project was completed in 1967, creating a massive reservoir.", te: "ఇంజనీరింగ్ యొక్క ఆధునిక అద్భుతం, ఈ ప్రాజెక్ట్ 1967లో పూర్తయింది, ఇది ఒక భారీ జలాశయాన్ని సృష్టించింది." },
    bestTimeToVisit: { en: "August to February, when the dam gates are often open.", te: "ఆగస్టు నుండి ఫిబ్రవరి వరకు, డ్యామ్ గేట్లు తరచుగా తెరిచి ఉంటాయి." },
    localCuisine: { en: "Local Telangana food, fresh fish from the reservoir.", te: "స్థానిక తెలంగాణ ఆహారం, జలాశయం నుండి తాజా చేపలు." },
    culturalEvents: { en: "Boating to Nagarjunakonda island, which houses a Buddhist museum.", te: "బౌద్ధ మ్యూజియం ఉన్న నాగార్జునకొండ ద్వీపానికి బోటింగ్." },
    distanceFromHyderabad: "Approx. 165 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "dam reservoir" }, { url: "https://placehold.co/400x300.png", hint: "dam gates" }],
    type: 'telangana',
  },
  {
    id: "pochampally",
    slug: "pochampally",
    name: { en: "Pochampally", te: "పోచంపల్లి" },
    description: { en: "A town famous for its traditional Ikat sarees, recognized as a World Craft Village.", te: "ప్రపంచ క్రాఫ్ట్ విలేజ్‌గా గుర్తింపు పొందిన, దాని సాంప్రదాయ ఇక్కత్ చీరలకు ప్రసిద్ధి చెందిన పట్టణం." },
    image: "https://images.unsplash.com/photo-1695150110878-a76e59db0b90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxwb2NoYW1wYWxseSUyMHZpbGxhZ2V8ZW58MHx8fHwxNzUzNjA0MTg3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "textile weaving",
    regionTags: ["Telangana", "Yadadri Bhuvanagiri"],
    historicalSignificance: { en: "The unique Ikat weaving tradition has been passed down for generations. The Bhoodan movement was also launched here.", te: "ప్రత్యేకమైన ఇక్కత్ నేత సంప్రదాయం తరతరాలుగా వస్తోంది. భూదాన్ ఉద్యమం కూడా ఇక్కడే ప్రారంభించబడింది." },
    bestTimeToVisit: { en: "Throughout the year.", te: "ఏడాది పొడవునా." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Visitors can observe the weaving process and purchase handcrafted textiles.", te: "సందర్శకులు నేత ప్రక్రియను గమనించవచ్చు మరియు చేతితో తయారు చేసిన వస్త్రాలను కొనుగోలు చేయవచ్చు." },
    distanceFromHyderabad: "Approx. 40 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ikat saree" }, { url: "https://placehold.co/400x300.png", hint: "handloom weaver" }],
    type: 'telangana',
  },
  {
    id: "manjira-wildlife-sanctuary",
    slug: "manjira-wildlife-sanctuary",
    name: { en: "Manjira Wildlife Sanctuary", te: "మంజీరా వన్యప్రాణుల అభయారణ్యం" },
    description: { en: "A riverine sanctuary that is home to a large population of mugger crocodiles and various bird species.", te: "మగ్గర్ మొసళ్ళు మరియు వివిధ పక్షి జాతులకు నిలయంగా ఉన్న ఒక నదీతీర అభయారణ్యం." },
    image: "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx3aWxkbGlmZXxlbnwwfHx8fDE3NTM2MDQzNDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "wildlife sanctuary",
    regionTags: ["Telangana", "Sangareddy"],
    historicalSignificance: { en: "Originally established to protect the mugger crocodile, it's now a haven for birdwatchers.", te: "వాస్తవానికి మగ్గర్ మొసలిని రక్షించడానికి స్థాపించబడింది, ఇది ఇప్పుడు పక్షి వీక్షకులకు ఒక స్వర్గధామం." },
    bestTimeToVisit: { en: "November to March, for bird watching.", te: "నవంబర్ నుండి మార్చి వరకు, పక్షులను చూడటానికి." },
    localCuisine: { en: "Not applicable within the sanctuary.", te: "అభయారణ్యం లోపల వర్తించదు." },
    culturalEvents: { en: "Boating and bird watching tours.", te: "బోటింగ్ మరియు పక్షులను చూసే పర్యటనలు." },
    distanceFromHyderabad: "Approx. 50 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "mugger crocodile" }, { url: "https://placehold.co/400x300.png", hint: "migratory birds" }],
    type: 'telangana',
  },
  {
    id: "bhongir-fort",
    slug: "bhongir-fort",
    name: { en: "Bhongir Fort", te: "భువనగిరి కోట" },
    description: { en: "A massive fort built on a monolithic rock by the Western Chalukya king Tribhuvanamalla Vikramaditya VI.", te: "పశ్చిమ చాళుక్య రాజు త్రిభువనమల్ల విక్రమాదిత్య VI చే ఒకే రాతిపై నిర్మించబడిన ఒక భారీ కోట." },
    image: "https://images.unsplash.com/photo-1706103780703-d044f10c30a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOHx8QmhvbmdpciUyMGZvcnR8ZW58MHx8fHwxNzUzNjA0MzczfDA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "hill fort",
    regionTags: ["Telangana", "Yadadri Bhuvanagiri"],
    historicalSignificance: { en: "The fort is associated with the rule of the Kakatiya queen Rudramadevi. It offers panoramic views from the top.", te: "ఈ కోట కాకతీయ రాణి రుద్రమదేవి పాలనతో ముడిపడి ఉంది. ఇది పై నుండి విస్తృత దృశ్యాలను అందిస్తుంది." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Local eateries in Bhongir town.", te: "భువనగిరి పట్టణంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "A popular destination for trekking and rock climbing.", te: "ట్రెక్కింగ్ మరియు రాక్ క్లైంబింగ్‌కు ఒక ప్రసిద్ధ గమ్యస్థానం." },
    distanceFromHyderabad: "Approx. 50 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "rock fortress" }, { url: "https://placehold.co/400x300.png", hint: "fort viewpoint" }],
    type: 'telangana',
  },
  {
    id: "medak-cathedral",
    slug: "medak-cathedral",
    name: { en: "Medak Cathedral", te: "మెదక్ కెథెడ్రల్" },
    description: { en: "One of the largest dioceses in Asia and the second-largest church in the world after the Vatican.", te: "ఆసియాలో అతిపెద్ద డయోసీస్‌లలో ఒకటి మరియు వాటికన్ తర్వాత ప్రపంచంలో రెండవ అతిపెద్ద చర్చి." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "large church",
    regionTags: ["Telangana", "Medak"],
    historicalSignificance: { en: "Built in Gothic Revival style, its construction took 10 years and was completed in 1924. The stained glass windows are a major attraction.", te: "గోతిక్ రివైవల్ శైలిలో నిర్మించబడింది, దీని నిర్మాణం 10 సంవత్సరాలు పట్టింది మరియు 1924లో పూర్తయింది. స్టెయిన్డ్ గ్లాస్ కిటికీలు ఒక ప్రధాన ఆకర్షణ." },
    bestTimeToVisit: { en: "Throughout the year, especially during Christmas.", te: "ఏడాది పొడవునా, ముఖ్యంగా క్రిస్మస్ సమయంలో." },
    localCuisine: { en: "Local food in Medak town.", te: "మెదక్ పట్టణంలో స్థానిక ఆహారం." },
    culturalEvents: { en: "Christmas celebrations are grand and attract many visitors.", te: "క్రిస్మస్ వేడుకలు ఘనంగా ఉంటాయి మరియు చాలా మంది సందర్శకులను ఆకర్షిస్తాయి." },
    distanceFromHyderabad: "Approx. 95 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "stained glass" }, { url: "https://placehold.co/400x300.png", hint: "church interior" }],
    type: 'telangana',
  },
  {
    id: "thousand-pillar-temple",
    slug: "thousand-pillar-temple",
    name: { en: "Thousand Pillar Temple", te: "వెయ్యి స్తంభాల గుడి" },
    description: { en: "A star-shaped temple renowned for its Kakatiyan architecture.", te: "కాకతీయ వాస్తుశిల్పానికి ప్రసిద్ధి చెందిన నక్షత్రాకార ఆలయం." },
    image: "https://images.unsplash.com/photo-1660463835177-bc6329055a6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxUaG91c2FuZCUyMHBpbGxhciUyMHRlbXBsZXxlbnwwfHx8fDE3NTM2MDQ0MTF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "pillar temple",
    regionTags: ["Telangana", "Warangal"],
    historicalSignificance: { en: "Built by King Rudra Deva in 1163 AD, it is dedicated to Lord Shiva, Vishnu, and Surya.", te: "క్రీ.శ. 1163లో రాజు రుద్ర దేవునిచే నిర్మించబడినది, ఇది శివుడు, విష్ణువు మరియు సూర్యునికి అంకితం చేయబడింది." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Warangal specialties.", te: "వరంగల్ ప్రత్యేకతలు." },
    culturalEvents: { en: "Maha Shivaratri is celebrated with great pomp.", te: "మహా శివరాత్రిని అత్యంత వైభవంగా జరుపుకుంటారు." },
    distanceFromHyderabad: "Approx. 150 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple carving" }, { url: "https://placehold.co/400x300.png", hint: "temple nandi" }],
    type: 'telangana',
  },
   {
    id: "birla-mandir",
    slug: "birla-mandir",
    name: { en: "Birla Mandir", te: "బిర్లా మందిర్" },
    description: { en: "A magnificent Hindu temple dedicated to Lord Venkateswara, built entirely of white marble.", te: "పూర్తిగా తెల్లని పాలరాతితో నిర్మించబడిన, శ్రీ వెంకటేశ్వర స్వామికి అంకితం చేయబడిన ఒక అద్భుతమైన హిందూ దేవాలయం." },
    image: "https://images.unsplash.com/photo-1701783470382-19eaea147ca7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxCaXJsYSUyMG1hbmRpcnxlbnwwfHx8fDE3NTM2MDQ0NDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    dataAiHint: "birla mandir",
    regionTags: ["Telangana", "Hyderabad"],
    historicalSignificance: { en: "Constructed in 1976 by the Birla Foundation, it blends Dravidian, Rajasthani and Utkala architectures.", te: "1976లో బిర్లా ఫౌండేషన్ ద్వారా నిర్మించబడినది, ఇది ద్రావిడ, రాజస్థానీ మరియు ఉత్కళ వాస్తుశిల్పాలను మిళితం చేస్తుంది." },
    bestTimeToVisit: { en: "Throughout the year, especially serene in the evenings.", te: "ఏడాది పొడవునా, ముఖ్యంగా సాయంత్రం వేళల్లో ప్రశాంతంగా ఉంటుంది." },
    localCuisine: { en: "Various restaurants are available in the vicinity.", te: "సమీపంలో వివిధ రెస్టారెంట్లు అందుబాటులో ఉన్నాయి." },
    culturalEvents: { en: "Major Hindu festivals like Janmashtami and Diwali are celebrated grandly.", te: "జన్మాష్టమి మరియు దీపావళి వంటి ప్రధాన హిందూ పండుగలను వైభవంగా జరుపుకుంటారు." },
    distanceFromHyderabad: "Located within Hyderabad city.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple marble" }, { url: "https://placehold.co/400x300.png", hint: "hyderabad skyline" }],
    type: 'telangana',
  },
  {
    id: "swarnagiri-temple",
    slug: "swarnagiri-temple",
    name: { en: "Swarnagiri Temple", te: "స్వర్ణగిరి దేవాలయం" },
    description: { en: "A recently constructed temple complex with impressive gopurams and architecture.", te: "ఆకట్టుకునే గోపురాలు మరియు వాస్తుశిల్పంతో ఇటీవల నిర్మించిన ఆలయ సముదాయం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "swarnagiri temple",
    regionTags: ["Telangana"],
    historicalSignificance: { en: "A modern architectural marvel, it has become a significant pilgrimage site in Telangana.", te: "ఒక ఆధునిక వాస్తుశిల్ప అద్భుతం, ఇది తెలంగాణలో ఒక ముఖ్యమైన పుణ్యక్షేత్రంగా మారింది." },
    bestTimeToVisit: { en: "October to February.", te: "అక్టోబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Temple prasadam and nearby local eateries.", te: "ఆలయ ప్రసాదం మరియు సమీపంలోని స్థానిక తినుబండారాలు." },
    culturalEvents: { en: "Major temple festivals and religious ceremonies.", te: "ప్రధాన ఆలయ ఉత్సవాలు మరియు మతపరమైన కార్యక్రమాలు." },
    distanceFromHyderabad: "Approx. 100 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "temple gopuram" }, { url: "https://placehold.co/400x300.png", hint: "temple sculpture" }],
    type: 'telangana',
  },
  {
    id: "suryapet",
    slug: "suryapet",
    name: { en: "Suryapet", te: "సూర్యాపేట" },
    description: { en: "Known as the 'Gateway of Telangana', it is a region with historical temples and sites.", te: "'తెలంగాణ ముఖద్వారం'గా పిలువబడే ఇది, చారిత్రక దేవాలయాలు మరియు ప్రదేశాలు ఉన్న ప్రాంతం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "historic town",
    regionTags: ["Telangana", "Suryapet"],
    historicalSignificance: { en: "The region has a rich history with evidence of Neolithic and Megalithic culture.", te: "ఈ ప్రాంతానికి నవీన శిలా మరియు బృహత్ శిలా సంస్కృతికి ఆధారాలున్న గొప్ప చరిత్ర ఉంది." },
    bestTimeToVisit: { en: "October to February.", te: "అక్టోబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Local Telangana cuisine.", te: "స్థానిక తెలంగాణ వంటకాలు." },
    culturalEvents: { en: "Various local jatras and festivals are celebrated throughout the year.", te: "ఏడాది పొడవునా వివిధ స్థానిక జాతరలు మరియు పండుగలు జరుపుకుంటారు." },
    distanceFromHyderabad: "Approx. 135 km.",
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ancient temple" }, { url: "https://placehold.co/400x300.png", hint: "rural landscape" }],
    type: 'telangana',
  }
];

export const indiaDestinations: Destination[] = [
  {
    id: "taj-mahal",
    slug: "taj-mahal",
    name: { en: "Taj Mahal", te: "తాజ్ మహల్" },
    description: { en: "An ivory-white marble mausoleum on the south bank of the Yamuna river in Agra.", te: "ఆగ్రాలోని యమునా నది దక్షిణ ఒడ్డున ఉన్న ఒక దంతపు-తెలుపు పాలరాతి సమాధి." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "taj mahal",
    regionTags: ["India", "Agra"],
    historicalSignificance: { en: "Commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal.", te: "1632లో మొఘల్ చక్రవర్తి షాజహాన్ చే తన అభిమాన భార్య ముంతాజ్ మహల్ సమాధిని ఉంచడానికి నిర్మించబడింది." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Petha, Mughlai cuisine.", te: "పేఠా, ముఘలాయ్ వంటకాలు." },
    culturalEvents: { en: "Taj Mahotsav in February.", te: "ఫిబ్రవరిలో తాజ్ మహోత్సవ్." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "mausoleum detail" }, { url: "https://placehold.co/400x300.png", hint: "yamuna river" }],
    type: 'india',
  },
  {
    id: "jaipur-city-palace",
    slug: "jaipur-city-palace",
    name: { en: "Jaipur City Palace", te: "జైపూర్ సిటీ ప్యాలెస్" },
    description: { en: "A palace complex in Jaipur, the capital of the Rajasthan state.", te: "రాజస్థాన్ రాష్ట్ర రాజధాని జైపూర్‌లోని ఒక రాజభవన సముదాయం." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "jaipur palace",
    regionTags: ["India", "Jaipur"],
    historicalSignificance: { en: "Established at the same time as the city of Jaipur, by Maharaja Sawai Jai Singh II.", te: "జైపూర్ నగరంతో పాటు అదే సమయంలో మహారాజా సవాయ్ జై సింగ్ II చే స్థాపించబడింది." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Dal Baati Churma, Ghewar.", te: "దాల్ బాటీ చుర్మా, ఘేవర్." },
    culturalEvents: { en: "Gangaur festival, Teej festival.", te: "గంగౌర్ పండుగ, తీజ్ పండుగ." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "palace courtyard" }, { url: "https://placehold.co/400x300.png", hint: "palace gates" }],
    type: 'india',
  },
  {
    id: "varanasi-ghats",
    slug: "varanasi-ghats",
    name: { en: "Varanasi Ghats", te: "వారణాసి ఘాట్లు" },
    description: { en: "Riverfront steps leading to the banks of the River Ganges.", te: "గంగా నది ఒడ్డుకు దారితీసే నదీతీర మెట్లు." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "varanasi ghats",
    regionTags: ["India", "Varanasi"],
    historicalSignificance: { en: "The ghats are an integral part of Varanasi's religious and cultural life, used for everything from bathing to cremation.", te: "ఈ ఘాట్లు వారణాసి యొక్క మత మరియు సాంస్కృతిక జీవితంలో ఒక అంతర్భాగం, స్నానం నుండి దహనం వరకు అన్నింటికీ ఉపయోగిస్తారు." },
    bestTimeToVisit: { en: "October to March.", te: "అక్టోబర్ నుండి మార్చి వరకు." },
    localCuisine: { en: "Kachori Sabzi, Lassi, Chaat.", te: "కచోరీ సబ్జీ, లస్సీ, చాట్." },
    culturalEvents: { en: "Ganga Aarti every evening, Dev Deepawali.", te: "ప్రతి సాయంత్రం గంగా హారతి, దేవ్ దీపావళి." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "ganga aarti" }, { url: "https://placehold.co/400x300.png", hint: "river boats" }],
    type: 'india',
  },
   {
    id: "goa-beaches",
    slug: "goa-beaches",
    name: { en: "Goa Beaches", te: "గోవా బీచ్‌లు" },
    description: { en: "Famous for its stunning coastline, vibrant nightlife, and Portuguese heritage.", te: "దాని అద్భుతమైన తీరప్రాంతం, ఉత్సాహభరితమైన రాత్రి జీవితం మరియు పోర్చుగీస్ వారసత్వానికి ప్రసిద్ధి." },
    image: "https://placehold.co/600x400.png",
    dataAiHint: "goa beach",
    regionTags: ["India", "Goa"],
    historicalSignificance: { en: "A former Portuguese colony, Goa's culture is a unique blend of Indian and European influences.", te: "ఒకప్పుడు పోర్చుగీస్ కాలనీ, గోవా సంస్కృతి భారతీయ మరియు యూరోపియన్ ప్రభావాల యొక్క ఒక ప్రత్యేకమైన మిశ్రమం." },
    bestTimeToVisit: { en: "November to February.", te: "నవంబర్ నుండి ఫిబ్రవరి వరకు." },
    localCuisine: { en: "Seafood, Vindaloo, Bebinca.", te: "సముద్రపు ఆహారం, విందాలూ, బెబింకా." },
    culturalEvents: { en: "Goa Carnival, Sunburn Festival.", te: "గోవా కార్నివాల్, సన్‌బర్న్ ఫెస్టివాల్." },
    distanceFromHyderabad: null,
    extraImages: [{ url: "https://placehold.co/400x300.png", hint: "beach sunset" }, { url: "https://placehold.co/400x300.png", hint: "goa church" }],
    type: 'india',
  }
];

export const allDestinations = [...telanganaDestinations, ...indiaDestinations];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return allDestinations.find((dest) => dest.slug === slug);
}
